hydra_discovery = {
    "issuer": "http://127.0.0.1:4444/",
    "authorization_endpoint": "http://127.0.0.1:4444/oauth2/auth",
    "token_endpoint": "http://127.0.0.1:4444/oauth2/token",
    "jwks_uri": "http://127.0.0.1:4444/.well-known/jwks.json",
    "subject_types_supported": ["pairwise", "public"],
    "response_types_supported": ["code", "code id_token", "id_token", "token id_token", "token", "token id_token code"],
    "claims_supported": ["sub"],
    "grant_types_supported": ["authorization_code", "implicit", "client_credentials", "refresh_token"],
    "response_modes_supported": ["query", "fragment"],
    "userinfo_endpoint": "http://127.0.0.1:4444/userinfo",
    "scopes_supported": ["offline_access", "offline", "openid"],
    "token_endpoint_auth_methods_supported": ["client_secret_post", "client_secret_basic", "private_key_jwt", "none"],
    "userinfo_signing_alg_values_supported": ["none", "RS256"],
    "id_token_signing_alg_values_supported": ["RS256"],
    "request_parameter_supported": True,
    "request_uri_parameter_supported": True,
    "require_request_uri_registration": True,
    "claims_parameter_supported": False,
    "revocation_endpoint": "http://127.0.0.1:4444/oauth2/revoke",
    "backchannel_logout_supported": True,
    "backchannel_logout_session_supported": True,
    "frontchannel_logout_supported": True,
    "frontchannel_logout_session_supported": True,
    "end_session_endpoint": "http://127.0.0.1:4444/oauth2/sessions/logout",
    "request_object_signing_alg_values_supported": ["RS256", "none"],
    "code_challenge_methods_supported": ["plain", "S256"],
}
